spring:
  application:
    name: foot-api

  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${DB_NAME}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # Options: none, validate, update, create, create-drop
      show-sql: true     # Affiche les requÃªtes SQL dans la console

key:
  replica: ${REPLICA_TOKEN}